services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # depends_on:
    #   - mysql
    #   - qdrant
    volumes:
      - ./backend/logs:/app/logs
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=ecommerce
    command: [ "uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000" ]
  