services:
  mysql:
    image: mysql:8.0
    environment:
      # MYSQL_USER: root
      # MYSQL_ROOT_PASSWORD: intent!
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      # PMA_USER: root
      # PMA_PASSWORD: 1234
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:v1.3.0
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  mysql_data:
  qdrant_data: